// Generated by FlutterFire CLI — run `flutterfire configure` to fill these in.
// Replace the placeholder values below with your actual Firebase project config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('DefaultFirebaseOptions not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCthKbZ8n3yuRQiG6Ykjhbt6YKksRygOJc',
    appId: '1:484126702525:android:396eb8db5975e98eeef0d4',
    messagingSenderId: '484126702525',
    projectId: 'meenzo-b6b92',
    storageBucket: 'meenzo-b6b92.firebasestorage.app',
  );

  // ── Add iOS app in Firebase Console → download GoogleService-Info.plist ───
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthKbZ8n3yuRQiG6Ykjhbt6YKksRygOJc',
    appId: '1:484126702525:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '484126702525',
    projectId: 'meenzo-b6b92',
    storageBucket: 'meenzo-b6b92.firebasestorage.app',
    iosBundleId: 'com.meenzo.app',
  );
}
